app.py
from flask import Flask, redirect, url_for, request, jsonify, render_template
import uuid
from flask_mail import Mail, Message
from user_account import user_account_blueprint

from services.database import db
from blueprints.users import view_users_blueprint

# enable cors
from flask_cors import CORS

app = Flask(__name__)
# app.config['CORS_HEADERS'] = 'Content-Type'
CORS(app)

# deploy flask
# https://dev.to/techparida/how-to-deploy-a-flask-app-on-heroku-heb

# you also need to add cors in blueprint
# reference:: 
"""
    # https://stackoverflow.com/questions/26980713/solve-cross-origin-resource-sharing-with-flask
    In case anyone is using blueprints, 
    you need to add the CORS() to each blueprint, 
    for example: my_blueprint = Blueprint('my_bp_name', name, url_prefix="/my-prefix") 
    CORS(my_blueprint) – BLang
"""

CORS(user_account_blueprint)

# CORS(user_account_blueprint)
# app.run(debug=True)

app.config['SECRET_KEY']='key'


@app.errorhandler(404)
def not_found(e):
    return render_template('notFound.html')


# https://medium.datadriveninvestor.com/authentication-flask-api-using-json-web-tokens-50104f2f1533
def start():
    response = {}
    response["Flask Server Response"] = "Flask App Running"
    response["Database is alive?"] = db.is_alive()
    
    return jsonify(response),200

def load_html():
    return render_template('index.html')

def display_about():
    return render_template('views/about.html')

# you need to specifiy view_func paramter.. 
app.add_url_rule('/about', view_func=display_about,methods=['GET'])

app.add_url_rule('/app', 'index',load_html,methods=['GET'])
app.register_blueprint(view_users_blueprint,endpoint="v",url_prefix="/view")

app.add_url_rule('/', 'index', load_html,methods=['GET'])

app.register_blueprint(user_account_blueprint,url_prefix="/api/user")


if __name__ == '__main__':
    # db = DatabaseManager()
    app.run(host='127.0.0.1', port=5000, debug=True)

blueprints/users.py
from flask import Flask, redirect, url_for, request, jsonify, render_template,Blueprint

view_users_blueprint = Blueprint('view_users',__name__)

def display_list(): 
    data=[
        {'name':'Audrin',},
        {'name': 'Stuvard'},
        {'name':'Eden',},
        {'name': 'Jonathan'},
        {'name':'Alex',},
        {'name': 'Dave'},
        {'name':'Dennis',},
        {'name': 'Enzo'},
    ]

    return render_template("users.html",result=data)
    # return '<h3>Rendered manually<h3>'


def display_user_log():
    # if i remember correctly arg , **args where args here are the data 
    # that can be reutrned so pwede multiple

    data = [
        {
            "user": "I think i lost my mind a while ago", 
            "bot": "cause I've been seeing some ghosts"
        },
        {
            "user": " and i'd be lying if i told you im not, cause i lie", 
            "bot": "these thoughts never speak out loud"
        },
        {
            "user": "Cause we've been driving so long i cant remember how we got here", 
            "bot": "Or how we survived for so long, try'na run from our pride till you set fire to the atmosphere"
        },
        {
            "user": "and I remember how we spent the 23rd feeling six feet under where im 30000 feet in the air", 
            "bot": "chasing the sun down so far east im west bound feeling like the edge of this world is near"
        }
    ]
    user_name = "Denis"

    return render_template("logs.html", logs=data , owner=user_name)

view_users_blueprint.add_url_rule('/users',view_func=display_list,methods=['GET'])
view_users_blueprint.add_url_rule('/user/log',view_func=display_user_log,methods=['GET'])

templates/components/footer.html
<footer>
  <div class="footer-container">
    <div class="footer-container-left">
      <div>Backend Monitor Tool</div>
    </div>
    <div class="footer-container-right">
      <div>Flask</div>
      <div>Postgresql</div>
      <div>HTML</div>
      <div>CSS</div>
    </div>
  </div>
</footer>

templates/components/header copy.html
<header class="header-sticky">
  <nav class="nav-horizontal">
    <div class="nav-toolbar">
      <div class="nav-title-area">
        <span class="nav-title-area-title"><a href="{{ url_for('index') }}">Title</a></span>
      </div>
    </div>
    
    <ul class="nav-menu-area">
      <li class="nav-menu-item" >Test</li>
      {# # <li class="nav-menu-item"><a role="li" href="{{url_for('view_users.display_list')}}">Users</a></li>
      #<li class="nav-menu-item"><a href="{{url_for('display_about')}}">About</a></li>
      #} 
    </ul>
   
  </nav>
</header>
    

templates/components/header.html
<header class="header-sticky">
  <nav class="nav-horizontal">
    <div class="nav-toolbar">
      <div class="nav-title-area">
        <span class="nav-title-area-title"><a href="{{ url_for('index') }}">Chatbot</a></span>
      </div>

      <ul class="nav-menu-area">

        {# namespace here in url_for('namespace',name) comes from the name of the blue print #}
        <li class="nav-menu-item"><a role="li" href="{{url_for('view_users.display_list')}}">Users</a></li>
        <li class="nav-menu-item"><a role="li" href="{{url_for('view_users.display_user_log')}}">Log Sample</a></li>
        <li class="nav-menu-item"><a href="{{url_for('display_about')}}">About</a></li>
      </ul>
    
    </div>
    <!-- end nav toolbar -->
   
  </nav>
</header>
    

templates/index.html
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/fix.css') }}"/>
  </head>
  <body>
    <div class="app-root">
      {% include "components/header.html" %}
      <main>
        <div class="layout-vertical">
            
          {% block main_content %}
            <h1>Main Page</h1>
            <p>Nothing goes here</p>
          {% endblock%}
          
          
          {% block content %}
          {% endblock  %}
        </div>
      </main>
      {% include "components/footer.html" %}
    </div>

  </body>

</html>

templates/logs.html
{% extends "index.html" %}

{% block main_content %}
  <div class="block-vertical" style="max-width: 70ch;">

    <h5>{{owner}} Chatlogs</h5>

    {% for log in logs%}
      <div class="block-vertical" style="margin-top: 1rem;">
        <span>Time: 2pm</span>
        <div class="bloc-vertical">
          <div>User</div>
          <div>{{log.user}}</div>
          &nbsp;
          <div>Bot</div>
          <div>{{log.bot}}</div>
        </div>
      </div>
    {% endfor %}  
  </div>    
{% endblock%}

templates/notFound.html
<h1>The page you are accessing is not found</h1>
<button>Sorry </button>

templates/users.html
{% extends "index.html" %}

{% block main_content %}


  <table>
    <caption>Tester Accounts </caption>
    <thead>
      <th>id</th>
      <th>name</th>
      <th>password</th>
      <th>date created</th>
      <th></th>
    </thead>
    
    <tbody>
      {# loop.index is a given variable to get the index of items looped#}
      {% for user in result %}    
        <tr >
          <td>{{loop.index}} </td>
          <td>{{user.name}}</td>
          <td>none</td>
          <td>none</td>
          <td><a href="{{ url_for('view_users.display_user_log')}}"><button>View Log</button></a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/views/about.html
{% extends "index.html" %}

{% block main_content %}
  <h1>About View Loaded</h1>
{% endblock %}